name: dev-time
base: core18
version: git
summary: Get the current local time of a GitHub user
description: |
  Get the current local time of a GitHub user:
    $ dev-time SamVerschueren
    19:47 - 8 Dec. 2015

    $ dev-time SamVerschueren sindresorhus
    SamVerschueren
      19:47 - 8 Dec. 2015
    sindresorhus
      18:47 - 8 Dec. 2015

    $ dev-time SamVerschueren -v
    19:47 - 8 Dec. 2015 - UTC+1

    $ dev-time SamVerschueren --format DD-MM-YYYY
    07-12-2015

grade: stable
confinement: strict

parts:
  dev-time:
    plugin: nodejs
    source: .
  git:
    # To use Git inside the snap.
    stage-packages: [git]
    plugin: nil
    organize:
      # Because usr/lib/git-core will not be on PATH.
      usr/lib/git-core/: usr/bin

apps:
  dev-time:
    command: dev-time
    plugs: [network]
